import { Header } from "@/components/Ui/Header";

import "@/app/globals.css";
import { Metadata } from "next";
import { LogoTipo } from "@/components/Ui/LogoTipo";

export const metadata: Metadata = {
    title: "Serena",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className="serena-bg-color">
                <Header colorFill="var(bg-color-01)">
                    <LogoTipo />
                </Header>
                {children}
            </body>
        </html>
    );
}
