import "@/app/globals.css";
import type { Metadata } from "next";
import { Header } from "../components/Header";
import { LogoTipo } from "../components/SerenaLogos/LogoTipo";
import { ButtonsList } from "../components/Ui/Feed/ButtonsList";
import { ButtonProvider } from "../context/ButtonContext";

export const metadata: Metadata = {
    title: "Serena | {}",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" className="">
            <body className="app-bg-color">
                <ButtonProvider>
                    <Header colorFill="var(--bg-color-01)">
                        <LogoTipo />
                        <ButtonsList />
                    </Header>
                    {children}
                </ButtonProvider>
            </body>
        </html>
    );
}
