import "@/app/globals.css";
import type { Metadata } from "next";
import { Header } from "@/app/components/Header";
import { LogoTipo } from "@/app/components/SerenaLogos/LogoTipo";
import { ButtonsList } from "@/app/components/Ui/Feed/ButtonsList";
import { PageNameProvider } from "@/app/context/PageNameContext";
import { SearchBarProvider } from "@/app/context/SearchContext";

export const metadata: Metadata = {
    title: "Serena",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" className="">
            <body className="app-bg-color">
                <PageNameProvider>
                    <Header colorFill="var(--bg-color-01)">
                        <LogoTipo />
                        <ButtonsList />
                    </Header>
                    <SearchBarProvider>{children}</SearchBarProvider>
                </PageNameProvider>
            </body>
        </html>
    );
}
