import { ModalProvider } from "@/context/ModalContext";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Serena",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" className="serena-bg-color">
            <body className="serena-bg-color">
                <ModalProvider>
                    {children}
                </ModalProvider>
            </body>
        </html>
    );
}
